### ISSUE TITLE
Упрощение первичного заведения юзеров

### ISSUE THREAD

**Issue by garikziv** [z-eos/umi#16]
С целью упрощения интерфейса первичного заведения юзера, стоит сделать чекбоксы таких сервисов как jabber, mail. Если требуется стандартное заведение, то домен будет совпадать с organisation и нет смысла это указыать несколько раз в разных местах, если нужно чтото "особенное", то милости просим обычным способом заполнять все по очереди

**Comment by z-eos** [comment]
done in commit 9378f191ef2c702e86db6e7945579bb9dbeee1ca
